### ISSUE TITLE
is it support chunk upload with large files like 1gb 5gb files?

### ISSUE THREAD

**Issue by gbox1** [animemoeus/pyscord-storage#221]

**Comment by animemoeus** [comment]
Yeah, already working on it 💪

![image](https://github.com/animemoeus/pyscord-storage/assets/33395829/e0b284a9-41b0-468d-a92d-d056e1cb450a)


Take a long time to finish coz I have some errands.

**Comment by animemoeus** [comment]
> Hello sir, Maam may i know how many days it will takes you to make code public?

https://github.com/animemoeus/unlimited-storage
