### ISSUE TITLE
Hosting service

### ISSUE THREAD

**Issue by codilau** [animemoeus/pyscord-storage#225]
Hey cool service, Is it possible to host a server though? I don't want to abuse your API

**Comment by animemoeus** [comment]
> Hey cool service, Is it possible to host a server though? I don't want to abuse your API

Do you mean to host the server on your own? 🤔

**Comment by codilau** [comment]
Yes, I wanted acces to the source so that I could use the API with my own token. I did solve though since yesterday. Basically you do a cdn_url = channel.send(file=file_object).attachments[0].url, right?

**Comment by animemoeus** [comment]
> Yes, I wanted acces to the source so that I could use the API with my own token. I did solve though since yesterday. Basically you do a cdn_url = channel.send(file=file_object).attachments[0].url, right?

yeah, correct 👍

something like that, hahaha

**Comment by animemoeus** [comment]
will create the new update for this package so that users can use the default API URL or their webhook URL
